---
- hosts: clients
  gather_facts: no
  remote_user: pirate
  become: yes
  become_method: sudo

  tasks:
  - name: run clients
    docker_container:
      name: client
      image: docker-repo:5000/tomitribe/pi-demo/client
      state: started
      restart: yes
      restart_policy: always
      pull: true
      env:
        JAVA_OPTS: "-Dmovie.client.readonly=true"
